WIP CAMEL-20593 - Use Apache kafka container image for tests
- Different Class for TestContainer to be used, the previously used was
deprecated https://java.testcontainers.org/modules/kafka/
- Zookeeper is no more available

Currently all idempotent tests are failing with
org.apache.camel.FailedToStartRouteException: Failed to start route
route1 because of java.lang.IllegalArgumentException: Target offsets
must be non-empty
	at org.apache.camel.impl.engine.RouteService.warmUp(RouteService.java:125)

Signed-off-by: Aurélien Pupier <apupier@redhat.com>